AWSTemplateFormatVersion: '2010-09-09'
Description: Fast Track - ECS Cluster Provisioning Template

# ---------------------------- Parameters
Parameters:
  Environment:
    Description: Environment Type
    Type: String
    Default: eval
    AllowedValues:
      - prod
      - mirror
      - stage
      - test
      - develop
      - eval
      - onetime

  EcsClusterName:
    Description: ECS Cluster Name
    Type: String

#---------------------------- Resources
Resources:
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref EcsClusterName
      Tags:
        -
          Key: Environment
          Value: !Ref Environment
