name: Status check workflow for Pull Request
on:
  pull_request:
    paths:
      - '**/*.ya?ml'
      - '!.github/**/*'
      - '!customizer/**.ya?ml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed_files
        run: |
          git fetch origin ${GITHUB_BASE_REF}
          changed_files="$(git diff origin/${GITHUB_BASE_REF}...${GITHUB_SHA} --name-only --diff-filter=AM -- '*.yaml' '*yml' ':(exclude).github/*' ':(exclude)customizer/*' | tr '\n' ' ')"
          echo "changed_files=${changed_files}" >> $GITHUB_ENV
      - name: Lint
        uses: ryof/cloudformation-lint-action@master
        with:
          args: ${{ env.changed_files }}
